import {
  Announcement,
  Evaluation,
  EventInfo,
  Judge,
  Participant,
  ProjectSubmission,
  Team,
  ActivityLog,
} from '@/types';

export const INITIAL_EVENT_INFO: EventInfo = {
  name: 'TechNova 2026',
  type: 'National Hackathon & Technology Summit',
  location: 'Mumbai, India',
  venue: 'Jio World Convention Centre, Hall 4 & Grand Arena',
  dates: 'August 29–30, 2026',
  currentDay: 'Day 1 of 2 — Hacking & Mentorship Phase',
  status: 'Check-in Live',
  submissionDeadline: '2026-08-30T10:00:00.000Z',
  prizePool: '₹25,00,000 (~$30,000 USD)',
  totalTracks: 4,
};

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'p-1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@technova.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P001-AARAV-MUMBAI',
    role: 'AI / ML Engineer',
    primaryTrack: 'AI & Intelligent Systems',
    skills: ['PyTorch', 'Transformers', 'FastAPI', 'LangChain', 'Python', 'CUDA'],
    interests: ['Autonomous Agents', 'Multimodal LLMs', 'Edge AI', 'Voice Interfaces'],
    experienceLevel: 'Advanced',
    availability: 'In a Team',
    bio: 'ML researcher passionate about agentic AI workflows and low-latency inference. Building next-gen assistive healthcare bots.',
    github: 'https://github.com/aarav-ai',
    linkedin: 'https://linkedin.com/in/aaravsharma-ai',
    portfolio: 'https://aaravsharma.dev',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T08:45:00.000Z',
    teamId: 'team-1',
    connectionRequestsSent: ['p-5', 'p-8'],
    connectionRequestsReceived: ['p-3', 'p-12'],
    connections: ['p-2', 'p-4'],
  },
  {
    id: 'p-2',
    name: 'Diya Sen',
    email: 'diya.sen@technova.io',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P002-DIYA-MUMBAI',
    role: 'UI/UX Designer & Product Lead',
    primaryTrack: 'AI & Intelligent Systems',
    skills: ['Figma', 'Design Systems', 'Next.js', 'Tailwind CSS', 'Framer Motion', 'User Research'],
    interests: ['Accessible Design', 'Micro-interactions', 'Voice UI', 'Data Visualization'],
    experienceLevel: 'Expert',
    availability: 'In a Team',
    bio: 'Lead product designer obsessed with intuitive user experiences for complex technical systems.',
    github: 'https://github.com/diyasen-design',
    linkedin: 'https://linkedin.com/in/diyasen',
    portfolio: 'https://diyasen.me',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T08:52:00.000Z',
    teamId: 'team-1',
    connectionRequestsSent: [],
    connectionRequestsReceived: ['p-7'],
    connections: ['p-1', 'p-4'],
  },
  {
    id: 'p-3',
    name: 'Rohan Deshmukh',
    email: 'rohan.d@technova.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P003-ROHAN-PUNE',
    role: 'Backend Architect',
    primaryTrack: 'Web3 & Fintech',
    skills: ['Go', 'Rust', 'PostgreSQL', 'Docker', 'Kubernetes', 'gRPC'],
    interests: ['Distributed Systems', 'Zero Knowledge Proofs', 'High-throughput Trading'],
    experienceLevel: 'Advanced',
    availability: 'Looking for Team',
    bio: 'Ex-fintech infrastructure engineer. Looking for an AI engineer or UI designer to build a decentralized settlement engine.',
    github: 'https://github.com/rohand-dev',
    linkedin: 'https://linkedin.com/in/rohandeshmukh',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T09:10:00.000Z',
    connectionRequestsSent: ['p-1'],
    connectionRequestsReceived: [],
    connections: [],
  },
  {
    id: 'p-4',
    name: 'Kavya Pillai',
    email: 'kavya.p@technova.io',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P004-KAVYA-BLR',
    role: 'Fullstack Developer',
    primaryTrack: 'AI & Intelligent Systems',
    skills: ['TypeScript', 'React', 'Node.js', 'GraphQL', 'AWS', 'Redis'],
    interests: ['Real-time Collaboration', 'Serverless', 'WebSockets'],
    experienceLevel: 'Intermediate',
    availability: 'In a Team',
    bio: 'Fullstack builder who loves turning prototype models into snappy, scalable web applications.',
    github: 'https://github.com/kavyapillai',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T09:15:00.000Z',
    teamId: 'team-1',
    connectionRequestsSent: [],
    connectionRequestsReceived: [],
    connections: ['p-1', 'p-2'],
  },
  {
    id: 'p-5',
    name: 'Arjun Mehta',
    email: 'arjun.m@technova.io',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P005-ARJUN-DELHI',
    role: 'AI / ML Engineer',
    primaryTrack: 'Healthcare & Biotech',
    skills: ['PyTorch', 'Computer Vision', 'OpenCV', 'TensorRT', 'Medical Imaging'],
    interests: ['Automated Diagnostics', 'Pathology AI', 'Federated Learning'],
    experienceLevel: 'Advanced',
    availability: 'In a Team',
    bio: 'Computer vision specialist working on early oncology screening via self-supervised vision models.',
    github: 'https://github.com/arjunmehta-cv',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T09:22:00.000Z',
    teamId: 'team-2',
    connectionRequestsSent: [],
    connectionRequestsReceived: ['p-1'],
    connections: ['p-6'],
  },
  {
    id: 'p-6',
    name: 'Ananya Verma',
    email: 'ananya.v@technova.io',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P006-ANANYA-HYD',
    role: 'Data Scientist & Bioinformatician',
    primaryTrack: 'Healthcare & Biotech',
    skills: ['Python', 'Biopython', 'R', 'Pandas', 'scikit-learn', 'Streamlit'],
    interests: ['Genomics', 'Drug Discovery', 'Clinical NLP'],
    experienceLevel: 'Intermediate',
    availability: 'In a Team',
    bio: 'Bridging computational biology and healthcare accessibility. Building AetherMed diagnostic tools.',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T09:30:00.000Z',
    teamId: 'team-2',
    connectionRequestsSent: [],
    connectionRequestsReceived: [],
    connections: ['p-5'],
  },
  {
    id: 'p-7',
    name: 'Vikramaditya Roy',
    email: 'vikram.roy@technova.io',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P007-VIKRAM-KOLKATA',
    role: 'Smart Contract & Solidity Dev',
    primaryTrack: 'Web3 & Fintech',
    skills: ['Solidity', 'Foundry', 'Ethereum', 'EVM Security', 'The Graph', 'Web3.js'],
    interests: ['DeFi Protocols', 'Smart Contract Auditing', 'Layer 2 Rollups'],
    experienceLevel: 'Expert',
    availability: 'In a Team',
    bio: 'Security researcher and DeFi builder. Audited 20+ protocols. Building zero-knowledge fraud audit tool.',
    github: 'https://github.com/vroy-sec',
    checkInStatus: 'not_checked_in',
    teamId: 'team-3',
    connectionRequestsSent: ['p-2'],
    connectionRequestsReceived: [],
    connections: ['p-8'],
  },
  {
    id: 'p-8',
    name: 'Tanya Kapoor',
    email: 'tanya.k@technova.io',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P008-TANYA-CHANDIGARH',
    role: 'Frontend Developer',
    primaryTrack: 'Web3 & Fintech',
    skills: ['React', 'Next.js', 'Wagmi', 'Ethers.js', 'Tailwind CSS', 'TypeScript'],
    interests: ['Decentralized UX', 'Gasless Transactions', 'Fintech Dashboards'],
    experienceLevel: 'Intermediate',
    availability: 'In a Team',
    bio: 'Web3 frontend specialist making crypto UX silky smooth and intuitive for mainstream users.',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T09:40:00.000Z',
    teamId: 'team-3',
    connectionRequestsSent: [],
    connectionRequestsReceived: ['p-1'],
    connections: ['p-7'],
  },
  {
    id: 'p-9',
    name: 'Sameer Kulkarni',
    email: 'sameer.k@technova.io',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P009-SAMEER-NAGPUR',
    role: 'Embedded Systems & IoT Engineer',
    primaryTrack: 'Sustainable Tech',
    skills: ['C++', 'Rust', 'ESP32', 'MQTT', 'LoRaWAN', 'Hardware Prototyping'],
    interests: ['Precision Agriculture', 'Renewable Energy Grids', 'Edge Compute'],
    experienceLevel: 'Advanced',
    availability: 'In a Team',
    bio: 'Hardware hacker designing ultra-low-power soil telemetry and microclimate nodes for farmers.',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T09:55:00.000Z',
    teamId: 'team-4',
    connectionRequestsSent: [],
    connectionRequestsReceived: [],
    connections: ['p-10'],
  },
  {
    id: 'p-10',
    name: 'Ishita Nair',
    email: 'ishita.nair@technova.io',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P010-ISHITA-KOCHI',
    role: 'Cloud Architect & Data Pipeline',
    primaryTrack: 'Sustainable Tech',
    skills: ['Python', 'GCP BigQuery', 'Apache Kafka', 'Terraform', 'React'],
    interests: ['Climate Tech', 'Carbon Tracking', 'Real-time Telemetry'],
    experienceLevel: 'Intermediate',
    availability: 'In a Team',
    bio: 'Building carbon accounting and IoT ingestion pipelines for decentralized ecological monitoring.',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T10:02:00.000Z',
    teamId: 'team-4',
    connectionRequestsSent: [],
    connectionRequestsReceived: [],
    connections: ['p-9'],
  },
  {
    id: 'p-11',
    name: 'Devansh Singhania',
    email: 'devansh.s@technova.io',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P011-DEVANSH-JAIPUR',
    role: 'Fullstack Developer',
    primaryTrack: 'AI & Intelligent Systems',
    skills: ['Next.js', 'Node.js', 'Python', 'Tailwind CSS', 'Supabase', 'OpenAI API'],
    interests: ['EdTech', 'Productivity Tools', 'Developer Experience'],
    experienceLevel: 'Intermediate',
    availability: 'Looking for Team',
    bio: 'Fullstack dev searching for a creative UI designer or ML engineer to build interactive knowledge graphs.',
    checkInStatus: 'not_checked_in',
    connectionRequestsSent: [],
    connectionRequestsReceived: [],
    connections: [],
  },
  {
    id: 'p-12',
    name: 'Meera Chawla',
    email: 'meera.c@technova.io',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P012-MEERA-AHMEDABAD',
    role: 'UI/UX Designer',
    primaryTrack: 'Sustainable Tech',
    skills: ['Figma', 'Adobe XD', 'Prototyping', 'HTML/CSS', 'Design Thinking'],
    interests: ['Circular Economy', 'Green UX', 'Visual Storytelling'],
    experienceLevel: 'Beginner',
    availability: 'Looking for Team',
    bio: 'Junior product designer eager to team up on sustainability or civic tech projects!',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T10:15:00.000Z',
    connectionRequestsSent: ['p-1'],
    connectionRequestsReceived: [],
    connections: [],
  },
  {
    id: 'p-13',
    name: 'Nikhil Rathi',
    email: 'nikhil.r@technova.io',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P013-NIKHIL-INDORE',
    role: 'Mobile Developer',
    primaryTrack: 'Healthcare & Biotech',
    skills: ['Flutter', 'Dart', 'Firebase', 'Bluetooth Low Energy', 'REST APIs'],
    interests: ['Wearables Integration', 'Health Tracking', 'Offline-first Apps'],
    experienceLevel: 'Intermediate',
    availability: 'Open to Offers',
    bio: 'Cross-platform mobile enthusiast with deep experience in BLE sensor synchronization.',
    checkInStatus: 'not_checked_in',
    connectionRequestsSent: [],
    connectionRequestsReceived: [],
    connections: [],
  },
  {
    id: 'p-14',
    name: 'Sneha Patel',
    email: 'sneha.p@technova.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P014-SNEHA-SURAT',
    role: 'Backend Architect',
    primaryTrack: 'AI & Intelligent Systems',
    skills: ['Python', 'FastAPI', 'Redis', 'Docker', 'Milvus Vector DB', 'Celery'],
    interests: ['Vector Databases', 'RAG Pipelines', 'Scalable Search'],
    experienceLevel: 'Advanced',
    availability: 'In a Team',
    bio: 'Vector DB aficionado. Optimized high-dimensional similarity search at sub-5ms latencies.',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T10:20:00.000Z',
    teamId: 'team-5',
    connectionRequestsSent: [],
    connectionRequestsReceived: [],
    connections: ['p-15'],
  },
  {
    id: 'p-15',
    name: 'Karan Joshi',
    email: 'karan.j@technova.io',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P015-KARAN-MUMBAI',
    role: 'AI / ML Engineer',
    primaryTrack: 'AI & Intelligent Systems',
    skills: ['PyTorch', 'LangChain', 'Llama 3', 'TypeScript', 'Next.js'],
    interests: ['Autonomous Code Review', 'Synthetic Data', 'Developer Tools'],
    experienceLevel: 'Advanced',
    availability: 'In a Team',
    bio: 'Working on automated semantic diff analysis and AI-augmented developer pairing.',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T10:25:00.000Z',
    teamId: 'team-5',
    connectionRequestsSent: [],
    connectionRequestsReceived: [],
    connections: ['p-14'],
  },
  {
    id: 'p-16',
    name: 'Ritika Bannerjee',
    email: 'ritika.b@technova.io',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P016-RITIKA-KOLKATA',
    role: 'Cybersecurity & Governance',
    primaryTrack: 'Web3 & Fintech',
    skills: ['Cryptography', 'Python', 'Wireshark', 'Smart Contract Auditing', 'ZK-SNARKs'],
    interests: ['Privacy-Preserving Tech', 'Identity Protocols', 'Financial Safety'],
    experienceLevel: 'Advanced',
    availability: 'In a Team',
    bio: 'Security analyst focusing on verifiable credentials and zero-knowledge identity assertions.',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T10:30:00.000Z',
    teamId: 'team-6',
    connectionRequestsSent: [],
    connectionRequestsReceived: [],
    connections: ['p-17'],
  },
  {
    id: 'p-17',
    name: 'Aditya Chopra',
    email: 'aditya.c@technova.io',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P017-ADITYA-LUCKNOW',
    role: 'Fullstack Developer',
    primaryTrack: 'Web3 & Fintech',
    skills: ['Next.js', 'Solidity', 'Tailwind CSS', 'Polygon ID', 'Node.js'],
    interests: ['Decentralized ID', 'Fintech Onboarding', 'Zero-Knowledge UX'],
    experienceLevel: 'Intermediate',
    availability: 'In a Team',
    bio: 'Passionate about simplifying cryptographic verification for ordinary retail consumers.',
    checkInStatus: 'checked_in',
    checkInTime: '2026-08-29T10:35:00.000Z',
    teamId: 'team-6',
    connectionRequestsSent: [],
    connectionRequestsReceived: [],
    connections: ['p-16'],
  },
  {
    id: 'p-18',
    name: 'Pooja Hegde',
    email: 'pooja.h@technova.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    qrToken: 'TN26-P018-POOJA-MANGALORE',
    role: 'Data Scientist',
    primaryTrack: 'Sustainable Tech',
    skills: ['Python', 'Spatial Analytics', 'QGIS', 'GeoPandas', 'Tableau'],
    interests: ['Disaster Modeling', 'Flood Risk Prediction', 'Satellite Analytics'],
    experienceLevel: 'Intermediate',
    availability: 'Looking for Team',
    bio: 'Geospatial data analyst passionate about flood resilience and climate disaster mitigation.',
    checkInStatus: 'not_checked_in',
    connectionRequestsSent: [],
    connectionRequestsReceived: [],
    connections: [],
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-1',
    name: 'NeuralCrafters',
    tagline: 'Multimodal AI co-pilot for intensive surgical workflow assistance',
    track: 'AI & Intelligent Systems',
    leaderId: 'p-1',
    members: [
      { participantId: 'p-1', name: 'Aarav Sharma', role: 'AI / ML Engineer', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', isLeader: true },
      { participantId: 'p-2', name: 'Diya Sen', role: 'UI/UX Designer & Product', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80', isLeader: false },
      { participantId: 'p-4', name: 'Kavya Pillai', role: 'Fullstack Developer', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80', isLeader: false },
    ],
    maxMembers: 4,
    lookingForRoles: ['Cloud & DevOps'],
    submissionId: 'sub-1',
    aggregateScore: 92.5,
    totalEvaluations: 3,
    rank: 1,
    previousRank: 1,
  },
  {
    id: 'team-2',
    name: 'AetherMed Diagnostics',
    tagline: 'Self-supervised multimodal oncology pre-screening at rural clinics',
    track: 'Healthcare & Biotech',
    leaderId: 'p-5',
    members: [
      { participantId: 'p-5', name: 'Arjun Mehta', role: 'AI / ML Engineer', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80', isLeader: true },
      { participantId: 'p-6', name: 'Ananya Verma', role: 'Data Scientist', avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80', isLeader: false },
    ],
    maxMembers: 4,
    lookingForRoles: ['Frontend Developer', 'Mobile Dev'],
    submissionId: 'sub-2',
    aggregateScore: 89.0,
    totalEvaluations: 3,
    rank: 2,
    previousRank: 3,
  },
  {
    id: 'team-3',
    name: 'BlockAudit 360',
    tagline: 'Automated ZK-formal verification and exploit prevention engine',
    track: 'Web3 & Fintech',
    leaderId: 'p-7',
    members: [
      { participantId: 'p-7', name: 'Vikramaditya Roy', role: 'Smart Contract Dev', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80', isLeader: true },
      { participantId: 'p-8', name: 'Tanya Kapoor', role: 'Frontend Developer', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80', isLeader: false },
    ],
    maxMembers: 4,
    lookingForRoles: ['Backend Architect'],
    submissionId: 'sub-3',
    aggregateScore: 86.5,
    totalEvaluations: 2,
    rank: 3,
    previousRank: 2,
  },
  {
    id: 'team-4',
    name: 'AgriSense Mesh',
    tagline: 'Decentralized LoRaWAN soil telemetry & micro-climate risk hedge',
    track: 'Sustainable Tech',
    leaderId: 'p-9',
    members: [
      { participantId: 'p-9', name: 'Sameer Kulkarni', role: 'IoT & Embedded', avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80', isLeader: true },
      { participantId: 'p-10', name: 'Ishita Nair', role: 'Cloud & Data Pipeline', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80', isLeader: false },
    ],
    maxMembers: 4,
    lookingForRoles: ['UI/UX Designer', 'Mobile Dev'],
    submissionId: 'sub-4',
    aggregateScore: 84.0,
    totalEvaluations: 2,
    rank: 4,
    previousRank: 4,
  },
  {
    id: 'team-5',
    name: 'CodeMorph AI',
    tagline: 'Autonomous contextual refactoring and security patching agent',
    track: 'AI & Intelligent Systems',
    leaderId: 'p-15',
    members: [
      { participantId: 'p-15', name: 'Karan Joshi', role: 'AI / ML Engineer', avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80', isLeader: true },
      { participantId: 'p-14', name: 'Sneha Patel', role: 'Backend Architect', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', isLeader: false },
    ],
    maxMembers: 4,
    lookingForRoles: ['Frontend Developer'],
    submissionId: 'sub-5',
    aggregateScore: 81.5,
    totalEvaluations: 2,
    rank: 5,
    previousRank: 5,
  },
  {
    id: 'team-6',
    name: 'ZK-Passport',
    tagline: 'Frictionless privacy-first digital KYC for cross-border remittances',
    track: 'Web3 & Fintech',
    leaderId: 'p-16',
    members: [
      { participantId: 'p-16', name: 'Ritika Bannerjee', role: 'Cybersecurity', avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=150&auto=format&fit=crop&q=80', isLeader: true },
      { participantId: 'p-17', name: 'Aditya Chopra', role: 'Fullstack Dev', avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80', isLeader: false },
    ],
    maxMembers: 4,
    lookingForRoles: ['UI/UX Designer'],
    submissionId: 'sub-6',
    aggregateScore: 78.0,
    totalEvaluations: 1,
    rank: 6,
    previousRank: 6,
  },
];

export const INITIAL_SUBMISSIONS: ProjectSubmission[] = [
  {
    id: 'sub-1',
    teamId: 'team-1',
    teamName: 'NeuralCrafters',
    title: 'SurgiVision AI: Real-Time Multimodal Surgical Assistance',
    tagline: 'Zero-latency edge vision and audio guidance for complex laparoscopic procedures.',
    track: 'AI & Intelligent Systems',
    problemStatement: 'Surgical teams operate under intense cognitive load during laparoscopic procedures with high complication risks. Current operating room setups lack real-time context-aware computer vision assistance to track instruments and verify anatomical landmarks.',
    solution: 'SurgiVision AI processes 60 FPS live laparoscopic video on local RTX/CUDA edge nodes, overlaying sub-millimeter anatomical risk zones, flagging artery proximity in real-time, and responding to hands-free voice inquiries via custom quantized LLM.',
    architectureNotes: 'PyTorch + TensorRT on edge runner; WebRTC ultra-low-latency streaming (<35ms); FastAPI orchestration; Next.js 14 Surgeon Glass Dashboard.',
    techStack: ['PyTorch', 'TensorRT', 'WebRTC', 'Next.js', 'FastAPI', 'CUDA', 'Tailwind CSS'],
    repoUrl: 'https://github.com/neuralcrafters/surgivision-technova',
    demoUrl: 'https://surgivision.technova.dev',
    videoUrl: 'https://youtube.com/watch?v=technova-surgivision-demo',
    slidesUrl: 'https://pitch.com/surgivision-technova-2026',
    status: 'evaluated',
    submittedAt: '2026-08-29T11:30:00.000Z',
    coverImage: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'sub-2',
    teamId: 'team-2',
    teamName: 'AetherMed Diagnostics',
    title: 'AetherScan: Self-Supervised Oncology Diagnostics for Rural Clinics',
    tagline: 'High-accuracy biopsy and dermatoscope image classification running offline on consumer hardware.',
    track: 'Healthcare & Biotech',
    problemStatement: 'Over 68% of rural clinics across South Asia lack access to on-site pathologists, causing weeks of fatal diagnostic delays for aggressive melanoma and cervical lesions.',
    solution: 'A federated self-supervised vision transformer pre-trained on 450,000 anonymized histopathology scans that runs completely offline on inexpensive tablets, producing explainable heatmaps in 1.4 seconds.',
    architectureNotes: 'ViT-Base with Grad-CAM visualization; ONNX runtime for offline mobile execution; Flutter front-end; encrypted local SQLite sync.',
    techStack: ['PyTorch', 'ONNX', 'Vision Transformers', 'Grad-CAM', 'Flutter', 'Python'],
    repoUrl: 'https://github.com/aethermed/aetherscan-ai',
    demoUrl: 'https://aetherscan.technova.dev',
    videoUrl: 'https://youtube.com/watch?v=technova-aetherscan',
    slidesUrl: 'https://speakerdeck.com/aethermed/technova-pitch',
    status: 'evaluated',
    submittedAt: '2026-08-29T11:45:00.000Z',
    coverImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'sub-3',
    teamId: 'team-3',
    teamName: 'BlockAudit 360',
    tagline: 'Automated ZK-formal verification and exploit prevention engine for EVM smart contracts.',
    track: 'Web3 & Fintech',
    problemStatement: 'Over $3.8 billion was drained in 2025 due to reentrancy vulnerabilities and flash loan price manipulation vectors that standard unit tests fail to catch.',
    solution: 'BlockAudit 360 uses symbolic execution paired with zero-knowledge property assertions to automatically generate proof-of-safety certificates and patch reentrancy vectors before mainnet deployment.',
    techStack: ['Solidity', 'Rust', 'Foundry', 'ZK-SNARKs', 'Next.js', 'Wagmi'],
    repoUrl: 'https://github.com/blockaudit360/engine',
    demoUrl: 'https://blockaudit360.technova.dev',
    videoUrl: 'https://youtube.com/watch?v=technova-blockaudit',
    status: 'evaluated',
    submittedAt: '2026-08-29T12:00:00.000Z',
    coverImage: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop&q=80',
    title: 'BlockAudit 360: Autonomous ZK-Proof Smart Contract Shield',
  },
  {
    id: 'sub-4',
    teamId: 'team-4',
    teamName: 'AgriSense Mesh',
    title: 'AgriSense: Decentralized Soil IoT & Parametric Micro-Insurance',
    tagline: 'Solar-powered mesh sensors triggering automated parametric drought payouts for smallholder farmers.',
    track: 'Sustainable Tech',
    problemStatement: 'Smallholder farmers lose an average of 42% of seasonal yield to erratic monsoon shifts with traditional insurance taking over 9 months to settle claims.',
    solution: 'Low-cost ESP32 solar mesh nodes monitor soil moisture and temperature via LoRaWAN, streaming cryptographically signed telemetry to smart contracts that execute instant micro-insurance claims when drought thresholds are reached.',
    techStack: ['C++', 'ESP32', 'LoRaWAN', 'FastAPI', 'Polygon', 'Tailwind CSS'],
    repoUrl: 'https://github.com/agrisense-mesh/core',
    demoUrl: 'https://agrisense.technova.dev',
    status: 'evaluated',
    submittedAt: '2026-08-29T12:15:00.000Z',
    coverImage: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'sub-5',
    teamId: 'team-5',
    teamName: 'CodeMorph AI',
    title: 'CodeMorph: Autonomous Architecture Refactoring & AST Migration',
    tagline: 'Self-healing code migration agent preserving unit test semantics across legacy enterprise codebases.',
    track: 'AI & Intelligent Systems',
    problemStatement: 'Enterprises spend millions migrating legacy Java/C++ codebases to modern TypeScript/Rust stacks with high regression rates.',
    solution: 'AST-aware agent that parses compiler trees, performs formal verification checks, and executes step-by-step modular code translation with zero hallucination.',
    techStack: ['Python', 'AST', 'Tree-Sitter', 'LangChain', 'Next.js', 'Docker'],
    repoUrl: 'https://github.com/codemorph/ast-agent',
    demoUrl: 'https://codemorph.technova.dev',
    status: 'under_review',
    submittedAt: '2026-08-29T12:30:00.000Z',
    coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'sub-6',
    teamId: 'team-6',
    teamName: 'ZK-Passport',
    title: 'ZK-Passport: Zero-Knowledge Sovereign Identity for Global Remittance',
    tagline: 'Prove identity, sanctions clearance, and creditworthiness without disclosing personal identifiers.',
    track: 'Web3 & Fintech',
    problemStatement: 'Cross-border remittances require redundant KYC submissions where users repeatedly upload sensitive passports to vulnerable databases.',
    solution: 'Generates zero-knowledge proofs from NFC biometric passport chips, enabling instant compliance checks without storing or transmitting raw identity data.',
    techStack: ['ZK-SNARKs', 'Circom', 'Solidity', 'Next.js', 'NFC Web API'],
    repoUrl: 'https://github.com/zk-passport/protocol',
    demoUrl: 'https://zkpassport.technova.dev',
    status: 'under_review',
    submittedAt: '2026-08-29T12:45:00.000Z',
    coverImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_JUDGES: Judge[] = [
  {
    id: 'j-1',
    name: 'Dr. Priya Sundaram',
    title: 'Senior Principal AI Researcher',
    company: 'Google DeepMind & IIT Bombay AI Lab',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    track: 'AI & Intelligent Systems',
    assignedSubmissionIds: ['sub-1', 'sub-2', 'sub-5'],
  },
  {
    id: 'j-2',
    name: 'Rajesh K. Varma',
    title: 'VP of Engineering & Web3 Fellow',
    company: 'Polygon Labs / Ex-Stripe',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    track: 'Web3 & Fintech',
    assignedSubmissionIds: ['sub-3', 'sub-6', 'sub-4'],
  },
  {
    id: 'j-3',
    name: 'Dr. Alistair Chen',
    title: 'Chief Medical Innovation Officer',
    company: 'BioHealth Ventures',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    track: 'Healthcare & Biotech',
    assignedSubmissionIds: ['sub-1', 'sub-2', 'sub-4'],
  },
  {
    id: 'j-4',
    name: 'Sunita Narain-Ghosh',
    title: 'Partner & Lead Climate Technologist',
    company: 'Nexus Cleantech Fund',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    track: 'Sustainable Tech',
    assignedSubmissionIds: ['sub-4', 'sub-1', 'sub-3'],
  },
];

export const INITIAL_EVALUATIONS: Evaluation[] = [
  {
    id: 'eval-1',
    submissionId: 'sub-1',
    teamId: 'team-1',
    judgeId: 'j-1',
    judgeName: 'Dr. Priya Sundaram',
    rubric: {
      innovation: 19,
      technicalImplementation: 24,
      problemRelevance: 19,
      userExperience: 14,
      impactAndFeasibility: 19,
    },
    totalScore: 95,
    feedback: 'Outstanding technical execution on the sub-35ms inference latency. The surgical risk overlay was exceptionally well thought out and demonstrated high practical feasibility.',
    strengths: ['Real-time TensorRT pipeline', 'Intuitive non-distracting UI', 'Clear clinical validation path'],
    improvementAreas: ['Needs edge case handling for smoke/lens fogging during cauterization'],
    evaluatedAt: '2026-08-29T13:15:00.000Z',
  },
  {
    id: 'eval-2',
    submissionId: 'sub-1',
    teamId: 'team-1',
    judgeId: 'j-3',
    judgeName: 'Dr. Alistair Chen',
    rubric: {
      innovation: 18,
      technicalImplementation: 23,
      problemRelevance: 20,
      userExperience: 13,
      impactAndFeasibility: 18,
    },
    totalScore: 92,
    feedback: 'Extremely strong clinical relevance. The voice interface during hands-busy situations was a very thoughtful touch.',
    strengths: ['Real-world laparoscopic video demo', 'Strong anatomical risk bounds'],
    improvementAreas: ['Clarify regulatory certification roadmap'],
    evaluatedAt: '2026-08-29T13:30:00.000Z',
  },
  {
    id: 'eval-3',
    submissionId: 'sub-2',
    teamId: 'team-2',
    judgeId: 'j-3',
    judgeName: 'Dr. Alistair Chen',
    rubric: {
      innovation: 17,
      technicalImplementation: 22,
      problemRelevance: 20,
      userExperience: 14,
      impactAndFeasibility: 18,
    },
    totalScore: 91,
    feedback: 'Incredible initiative solving real rural diagnostic bottlenecks. The offline tablet capability makes this truly viable.',
    strengths: ['Complete offline ONNX inference', 'Grad-CAM explainability'],
    improvementAreas: ['Expand dataset to broader skin pigmentation variety'],
    evaluatedAt: '2026-08-29T13:45:00.000Z',
  },
  {
    id: 'eval-4',
    submissionId: 'sub-3',
    teamId: 'team-3',
    judgeId: 'j-2',
    judgeName: 'Rajesh K. Varma',
    rubric: {
      innovation: 18,
      technicalImplementation: 23,
      problemRelevance: 17,
      userExperience: 12,
      impactAndFeasibility: 18,
    },
    totalScore: 88,
    feedback: 'Impressive formal verification proofs. The automated exploit synthesizer found 3 edge cases on standard ERC-4626 vaults.',
    strengths: ['Symbolic execution engine', 'Clean Solidity integration'],
    improvementAreas: ['UI could be simplified for junior contract developers'],
    evaluatedAt: '2026-08-29T14:00:00.000Z',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: '⚠️ VENUE UPDATE: Keynote & Mentor Pods Relocation',
    message: 'The AI & Healthcare mentor breakout clinics have shifted to Arena Hall B (2nd floor). Please check your badge colors for access.',
    priority: 'critical',
    category: 'venue',
    timestamp: '2026-08-29T10:30:00.000Z',
    author: 'Vikram Malhotra (Lead Organizer)',
    pinned: true,
  },
  {
    id: 'ann-2',
    title: '⏱️ Project Submission Portal Open (Deadline: 10:00 AM Tomorrow)',
    message: 'All teams must submit your GitHub repository, live demo URL, and 2-minute video pitch through the Project Submission tab before 10:00 AM on Sunday, August 30.',
    priority: 'high',
    category: 'submission',
    timestamp: '2026-08-29T11:00:00.000Z',
    author: 'TechNova Organizing Committee',
    pinned: true,
  },
  {
    id: 'ann-3',
    title: '☕ Midnight Energy Refuel & Cloud Credits Drop',
    message: 'Complimentary cloud credits ($500 GCP & $200 NVIDIA GPU vouchers) are now active in your participant profile. Midnight pizza and espresso bar starts at 11:30 PM!',
    priority: 'normal',
    category: 'general',
    timestamp: '2026-08-29T12:00:00.000Z',
    author: 'Community Team',
  },
  {
    id: 'ann-4',
    title: '🤖 1-on-1 DeepMind & Polygon Mentorship Slots Live',
    message: 'Book a 15-minute code review and pitch rehearsal with industry mentors at the Mentor Desk.',
    priority: 'normal',
    category: 'mentorship',
    timestamp: '2026-08-29T12:30:00.000Z',
    author: 'Mentorship Ops',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    type: 'check_in',
    title: 'Participant Verified',
    description: 'Aarav Sharma checked in via QR pass at Desk #3',
    timestamp: '2026-08-29T08:45:00.000Z',
  },
  {
    id: 'act-2',
    type: 'team_create',
    title: 'Team Registered',
    description: 'Team "NeuralCrafters" formed with 3 members in AI & Intelligent Systems',
    timestamp: '2026-08-29T09:00:00.000Z',
  },
  {
    id: 'act-3',
    type: 'check_in',
    title: 'Participant Verified',
    description: 'Diya Sen checked in via QR pass at Desk #1',
    timestamp: '2026-08-29T09:12:00.000Z',
  },
  {
    id: 'act-4',
    type: 'submission',
    title: 'Project Submitted',
    description: 'NeuralCrafters submitted "SurgiVision AI: Real-Time Multimodal Surgical Assistance"',
    timestamp: '2026-08-29T11:30:00.000Z',
  },
  {
    id: 'act-5',
    type: 'announcement',
    title: 'Broadcast Published',
    description: 'Organizer published critical venue update for Arena Hall B',
    timestamp: '2026-08-29T10:30:00.000Z',
  },
  {
    id: 'act-6',
    type: 'evaluation',
    title: 'Score Submitted',
    description: 'Dr. Priya Sundaram scored SurgiVision AI: 95/100 points',
    timestamp: '2026-08-29T13:15:00.000Z',
  },
];
