import {
  Announcement,
  CategoryItem,
  CertificateRecord,
  EventFeedback,
  EventInfo,
  EventItem,
  Judge,
  NotificationItem,
  Participant,
  ProjectSubmission,
  RegistrationRecord,
  Team,
  UserAccount,
  VenueItem,
  VolunteerAssignment,
  ActivityLog,
  Evaluation,
} from '@/types';

// ================= MASTER CATEGORIES (FR21) =================
export const INITIAL_CATEGORIES: CategoryItem[] = [
  {
    id: 'cat-tech',
    name: 'Technical',
    description: 'Hackathons, coding contests, algorithmic showdowns, and engineering challenges.',
    icon: 'Terminal',
    color: '#2563eb', // University Blue
    eventCount: 2,
  },
  {
    id: 'cat-workshops',
    name: 'Workshop',
    description: 'Hands-on practical sessions, lab tutorials, and interactive skill-building bootcamps.',
    icon: 'Cpu',
    color: '#059669', // Forest Emerald
    eventCount: 2,
  },
  {
    id: 'cat-seminars',
    name: 'Seminar',
    description: 'Guest lectures, expert panel discussions, keynote addresses, and research symposiums.',
    icon: 'BookOpen',
    color: '#7c3aed', // Slate Purple
    eventCount: 1,
  },
  {
    id: 'cat-cultural',
    name: 'Cultural',
    description: 'Music performances, theater arts, dance competitions, literature, and campus fests.',
    icon: 'Music',
    color: '#db2777', // Crimson Rose
    eventCount: 1,
  },
  {
    id: 'cat-academic',
    name: 'Academic',
    description: 'Department summits, inter-collegiate conferences, thesis defense, and academic forums.',
    icon: 'GraduationCap',
    color: '#d97706', // Honey Amber
    eventCount: 1,
  },
  {
    id: 'cat-sports',
    name: 'Sports',
    description: 'Chess tournaments, e-sports, athletics meets, and campus sports league matches.',
    icon: 'Trophy',
    color: '#0891b2', // Ocean Cyan
    eventCount: 1,
  },
];

// ================= MASTER VENUES (FR21) - RAMNARAIN RUIA AUTONOMOUS COLLEGE =================
export const INITIAL_VENUES: VenueItem[] = [
  {
    id: 'ven-1',
    name: 'Ruia College Auditorium',
    building: 'Heritage Main Building, Ground Floor',
    capacity: 600,
    facilities: ['Stage Acoustics', 'Dual Laser Projectors', 'Central Air Conditioning', 'Green Rooms', 'Wheelchair Access'],
    status: 'available',
  },
  {
    id: 'ven-2',
    name: 'Dr. S. Radhakrishnan Seminar Hall',
    building: 'Main Academic Building, 1st Floor',
    capacity: 200,
    facilities: ['Podium Mic & PA System', 'Livestreaming Rig', 'High-Speed Campus Wi-Fi', 'Interactive Display'],
    status: 'available',
  },
  {
    id: 'ven-3',
    name: 'Computer Science & IT Lab 4',
    building: 'Science Wing, 3rd Floor',
    capacity: 100,
    facilities: ['100 High-Performance Workstations', 'Gigabit Ethernet', 'Power Backup (UPS)', 'Smart Projector'],
    status: 'available',
  },
  {
    id: 'ven-4',
    name: 'Historic Ruia Quadrangle & Open Stage',
    building: 'Campus Central Quadrangle',
    capacity: 1500,
    facilities: ['Open-Air Amphitheatre Stage', 'Perimeter Floodlighting', 'Concert Sound Console'],
    status: 'available',
  },
  {
    id: 'ven-5',
    name: 'DDU Kaushal Kendra & Bio-analytical Lab',
    building: 'Vocational & Research Block, 2nd Floor',
    capacity: 60,
    facilities: ['Bio-Analytical Instruments', 'Rapid Prototyping Workstations', 'Modular Desks', 'Smart Board'],
    status: 'available',
  },
  {
    id: 'ven-6',
    name: 'Ruia Sports Academy & Gymkhana',
    building: 'Gymkhana Complex',
    capacity: 250,
    facilities: ['Indoor Badminton & TT Courts', 'Chess Arena', 'Multi-Purpose Stage', 'Sound System'],
    status: 'available',
  },
];

// ================= USER ACCOUNTS (FR1, FR2, FR25) =================
export const INITIAL_USERS: UserAccount[] = [
  // Students
  {
    id: 'usr-student-1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@ruiacollege.edu',
    role: 'student',
    department: 'Computer Science & IT',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    studentIdNumber: 'RUIA-2023-CS084',
    phone: '+91 98201 44512',
    bookmarkedEventIds: ['evt-1', 'evt-3'],
  },
  {
    id: 'usr-student-2',
    name: 'Diya Sen',
    email: 'diya.sen@ruiacollege.edu',
    role: 'student',
    department: 'Computer Science & IT',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    studentIdNumber: 'RUIA-2023-IT042',
    phone: '+91 98334 11209',
    bookmarkedEventIds: ['evt-1', 'evt-4'],
  },
  {
    id: 'usr-student-3',
    name: 'Rohan Deshmukh',
    email: 'rohan.d@ruiacollege.edu',
    role: 'student',
    department: 'Bioanalytical Sciences & Chemistry',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    studentIdNumber: 'RUIA-2024-EC105',
    phone: '+91 97652 88401',
    bookmarkedEventIds: ['evt-2'],
  },
  {
    id: 'usr-student-4',
    name: 'Kavya Pillai',
    email: 'kavya.p@ruiacollege.edu',
    role: 'student',
    department: 'Computer Science & IT',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    studentIdNumber: 'RUIA-2023-CS019',
    phone: '+91 99204 77310',
    bookmarkedEventIds: ['evt-1'],
  },

  // Organizers
  {
    id: 'usr-organizer-1',
    name: 'Priya Rao',
    email: 'priya.rao@ruiacollege.edu',
    role: 'organizer',
    department: 'Ruia Cultural Association & Student Council',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    phone: '+91 98190 22345',
    bookmarkedEventIds: [],
  },
  {
    id: 'usr-organizer-2',
    name: 'Vikram Malhotra',
    email: 'vikram.m@ruiacollege.edu',
    role: 'organizer',
    department: 'Department of Computer Science & IT',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    phone: '+91 98205 33490',
    bookmarkedEventIds: [],
  },

  // Admins
  {
    id: 'usr-admin-1',
    name: 'Dr. Anushree Lokur',
    email: 'principal@ruiacollege.edu',
    role: 'admin',
    department: 'Office of the Principal • Ramnarain Ruia Autonomous College',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    phone: '+91 22 2414 3098',
    bookmarkedEventIds: [],
  },
  {
    id: 'usr-admin-2',
    name: 'Prof. Rajesh Nair',
    email: 'registrar@ruiacollege.edu',
    role: 'admin',
    department: 'Academic Administration & Examination Cell',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    phone: '+91 22 2414 3099',
    bookmarkedEventIds: [],
  },
];

// ================= EVENTS DATA (FR3, FR4, FR5, FR6, FR7, FR11, FR13, FR24) =================
export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt-1',
    title: 'TechNova 2026: National Hackathon & Innovation Summit',
    description:
      'The premier 36-hour inter-collegiate software hackathon. Students collaborate in teams to build functional prototypes tackling real-world problems in AI, Web3, Healthcare, and Sustainable Technologies.',
    category: 'Technical',
    venueId: 'ven-3',
    venueName: 'Computer Science & IT Lab 4 & Ruia Auditorium',
    building: 'Science Wing & Heritage Main Building',
    bannerImage:
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=80',
    startDate: '2026-10-15T09:00:00Z',
    endDate: '2026-10-16T21:00:00Z',
    registrationDeadline: '2026-10-10T23:59:59Z',
    capacity: 250,
    registeredCount: 218,
    price: 0, // Free
    status: 'published',
    organizerId: 'usr-organizer-1',
    organizerName: 'Priya Rao (Lead Tech Coordinator)',
    organizerContact: {
      name: 'Priya Rao',
      email: 'technova-queries@ruiacollege.edu',
      phone: '+91 98190 22345',
      department: 'Ruia Technical Council',
    },
    scheduleTimeline: [
      { id: 'sch-1', time: 'Day 1 • 08:30 AM', title: 'Registration & Gate Pass Verification', room: 'Main Entrance Foyer', speaker: 'Volunteer Desk A' },
      { id: 'sch-2', time: 'Day 1 • 09:30 AM', title: 'Opening Keynote & Problem Statements Release', room: 'Ruia College Auditorium', speaker: 'Dr. Anushree Lokur & Industry Mentors' },
      { id: 'sch-3', time: 'Day 1 • 11:00 AM', title: 'Hacking Commences & Team Matchmaking', room: 'CS & IT Lab 4', speaker: 'Track Mentors' },
      { id: 'sch-4', time: 'Day 1 • 04:30 PM', title: 'Mentorship Calibration Checkpoint 1', room: 'Lab Workstations', speaker: 'Domain Experts' },
      { id: 'sch-5', time: 'Day 2 • 02:00 PM', title: 'Code Freeze & Project Submission Deadline', room: 'Online Portal', speaker: 'Submissions Desk' },
      { id: 'sch-6', time: 'Day 2 • 04:00 PM', title: 'Jury Evaluation & Pitch Rounds', room: 'Radhakrishnan Seminar Hall', speaker: 'Evaluation Jury' },
      { id: 'sch-7', time: 'Day 2 • 07:00 PM', title: 'Grand Award Ceremony & Valedictory', room: 'Ruia College Auditorium', speaker: 'Dr. Anushree Lokur, Principal' },
    ],
    tags: ['Hackathon', 'AI / ML', 'Web3', 'Competitive Coding', 'Prizes'],
    isHackathon: true,
  },
  {
    id: 'evt-2',
    title: 'Cyber Defense & Ethical Hacking Hands-on Symposium',
    description:
      'A master workshop on offensive and defensive cybersecurity techniques. Covers real-world penetration testing, network traffic forensics, zero-day mitigation, and red-team vs blue-team simulations.',
    category: 'Seminar',
    venueId: 'ven-2',
    venueName: 'Dr. S. Radhakrishnan Seminar Hall',
    building: 'Main Academic Building',
    bannerImage:
      'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=80',
    startDate: '2026-10-22T10:00:00Z',
    endDate: '2026-10-22T17:00:00Z',
    registrationDeadline: '2026-10-20T18:00:00Z',
    capacity: 200,
    registeredCount: 165,
    price: 150, // Paid event
    status: 'published',
    organizerId: 'usr-organizer-2',
    organizerName: 'Vikram Malhotra',
    organizerContact: {
      name: 'Vikram Malhotra',
      email: 'cybersec-symposium@ruiacollege.edu',
      phone: '+91 98205 33490',
      department: 'Dept of Computer Science & IT',
    },
    scheduleTimeline: [
      { id: 'sch-201', time: '10:00 AM - 11:30 AM', title: 'State of Global Cyber Attacks in 2026', room: 'Seminar Hall Pod A', speaker: 'Chief Security Officer, SafeNet Corp' },
      { id: 'sch-202', time: '11:45 AM - 01:15 PM', title: 'Hands-on Packet Analysis & Burp Suite Testing', room: 'Seminar Hall Pod A', speaker: 'Vikram Malhotra' },
      { id: 'sch-203', time: '02:00 PM - 04:30 PM', title: 'Interactive Capture The Flag (CTF) Drill', room: 'CS & IT Lab 4', speaker: 'Ruia CyberSec Team' },
      { id: 'sch-204', time: '04:30 PM - 05:00 PM', title: 'Certificates of Participation & Q&A', room: 'Seminar Hall Pod A', speaker: 'Department Head' },
    ],
    tags: ['Security', 'Ethical Hacking', 'Hands-on', 'CTF', 'Industry Speaker'],
    isHackathon: false,
  },
  {
    id: 'evt-3',
    title: 'Generative AI & Agentic Systems Masterclass',
    description:
      'Deep dive into building reliable agentic applications using state-of-the-art LLMs, multi-agent orchestration frameworks, function calling, vector databases, and real-time inference optimization.',
    category: 'Workshop',
    venueId: 'ven-3',
    venueName: 'Computer Science & IT Lab 4',
    building: 'Science Wing, 3rd Floor',
    bannerImage:
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    startDate: '2026-10-28T13:00:00Z',
    endDate: '2026-10-28T18:00:00Z',
    registrationDeadline: '2026-10-26T23:59:59Z',
    capacity: 100,
    registeredCount: 94,
    price: 200, // Paid event
    status: 'published',
    organizerId: 'usr-organizer-1',
    organizerName: 'Priya Rao',
    organizerContact: {
      name: 'Priya Rao',
      email: 'ai-masterclass@ruiacollege.edu',
      phone: '+91 98190 22345',
      department: 'Ruia AI Student Research Chapter',
    },
    scheduleTimeline: [
      { id: 'sch-301', time: '01:00 PM - 02:30 PM', title: 'Architecting LLM Agents with Structured Tools', room: 'Lab Workstations', speaker: 'Dr. Arjun Mehta' },
      { id: 'sch-302', time: '02:45 PM - 04:15 PM', title: 'Memory, RAG & Long-Context Strategies', room: 'Lab Workstations', speaker: 'Priya Rao' },
      { id: 'sch-303', time: '04:30 PM - 05:45 PM', title: 'Live Agent Deployment & Evaluation Benchmarks', room: 'Lab Workstations', speaker: 'Guest AI Researcher' },
    ],
    tags: ['AI', 'Machine Learning', 'LLMs', 'Python', 'Hands-on'],
    isHackathon: false,
  },
  {
    id: 'evt-4',
    title: 'Aarohan 2026: Annual Inter-Collegiate Cultural Festival',
    description:
      'The flagship cultural festival of Ramnarain Ruia Autonomous College. Three days packed with competitive music battles, classical dance showcases, street play (Nukkad Natak), fine arts exhibitions, and an electrifying celebrity evening.',
    category: 'Cultural',
    venueId: 'ven-4',
    venueName: 'Historic Ruia Quadrangle & Open Stage',
    building: 'Campus Central Quadrangle',
    bannerImage:
      'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop&q=80',
    startDate: '2026-11-06T16:00:00Z',
    endDate: '2026-11-07T22:30:00Z',
    registrationDeadline: '2026-11-04T23:59:59Z',
    capacity: 1500,
    registeredCount: 1240,
    price: 0, // Free
    status: 'published',
    organizerId: 'usr-organizer-1',
    organizerName: 'Ruia Cultural Association',
    organizerContact: {
      name: 'Cultural Secretary',
      email: 'aarohan-fest@ruiacollege.edu',
      phone: '+91 22 2414 3098',
      department: 'Ruia Cultural Association',
    },
    scheduleTimeline: [
      { id: 'sch-401', time: 'Day 1 • 04:00 PM', title: 'Inaugural Gala & Campus Band Prelims', room: 'Quadrangle Stage 1', speaker: 'Cultural Council' },
      { id: 'sch-402', time: 'Day 1 • 07:00 PM', title: 'Inter-Collegiate Dance Extravaganza', room: 'Quadrangle Main Stage', speaker: 'Guest Judges' },
      { id: 'sch-403', time: 'Day 2 • 02:00 PM', title: 'Street Theatre (Nukkad Natak) Finals', room: 'Heritage Porch Courtyard', speaker: 'Ruia Natyavalay' },
      { id: 'sch-404', time: 'Day 2 • 06:30 PM', title: 'Celebrity Musical Night & Light Show', room: 'Quadrangle Main Stage', speaker: 'Headline Artist' },
    ],
    tags: ['Aarohan', 'Music', 'Dance', 'Festival', 'Free Entry', 'Campus Life'],
    isHackathon: false,
  },
  {
    id: 'evt-5',
    title: 'Robotics & Autonomous Quadcopter Bootcamp',
    description:
      'Learn hardware assembly, embedded C++ programming on STM32 boards, PID flight controller tuning, and basic computer vision integration for autonomous waypoint drone navigation.',
    category: 'Workshop',
    venueId: 'ven-5',
    venueName: 'DDU Kaushal Kendra & Bio-analytical Lab',
    building: 'Vocational & Research Block',
    bannerImage:
      'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80',
    startDate: '2026-11-14T09:30:00Z',
    endDate: '2026-11-15T16:30:00Z',
    registrationDeadline: '2026-11-10T18:00:00Z',
    capacity: 60,
    registeredCount: 18,
    price: 350,
    status: 'pending_approval', // Pending admin review (FR4 Showcase)
    organizerId: 'usr-organizer-2',
    organizerName: 'Vikram Malhotra',
    organizerContact: {
      name: 'Vikram Malhotra',
      email: 'robotics-bootcamp@ruiacollege.edu',
      phone: '+91 98205 33490',
      department: 'Ruia Robotics & Automation Club',
    },
    scheduleTimeline: [
      { id: 'sch-501', time: 'Day 1 • 09:30 AM', title: 'Hardware Architecture & Motor Aerodynamics', room: 'Kaushal Kendra Bench 1', speaker: 'Robotics Faculty' },
      { id: 'sch-502', time: 'Day 1 • 01:30 PM', title: 'Firmware Flashing & ESC Calibration Lab', room: 'Kaushal Kendra Workstations', speaker: 'Vikram Malhotra' },
      { id: 'sch-503', time: 'Day 2 • 10:00 AM', title: 'Autonomous Flight Tests & Obstacle Course', room: 'Gymkhana Grounds', speaker: 'Flight Marshals' },
    ],
    tags: ['Hardware', 'Robotics', 'Drones', 'C++', 'Lab Workshop'],
    isHackathon: false,
  },
  {
    id: 'evt-6',
    title: 'Principal’s Annual Academic & Innovation Summit',
    description:
      'A formal campus-wide symposium highlighting student academic accomplishments, faculty research grants, patents filed, and an open forum with industry recruiters and Ramnarain Ruia Autonomous College leadership.',
    category: 'Academic',
    venueId: 'ven-1',
    venueName: 'Ruia College Auditorium',
    building: 'Heritage Main Building',
    bannerImage:
      'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&auto=format&fit=crop&q=80',
    startDate: '2026-09-10T09:00:00Z',
    endDate: '2026-09-10T17:00:00Z',
    registrationDeadline: '2026-09-05T23:59:59Z',
    capacity: 500,
    registeredCount: 462,
    price: 0,
    status: 'completed', // Completed event with certificates ready (FR17 & FR18 Showcase)
    organizerId: 'usr-admin-1',
    organizerName: 'Dr. Anushree Lokur (Principal)',
    organizerContact: {
      name: 'Office of the Principal',
      email: 'principal@ruiacollege.edu',
      phone: '+91 22 2414 3098',
      department: 'Office of the Principal',
    },
    scheduleTimeline: [
      { id: 'sch-601', time: '09:00 AM - 10:30 AM', title: 'Principal’s Address & Year in Review Report', room: 'Ruia College Auditorium', speaker: 'Dr. Anushree Lokur' },
      { id: 'sch-602', time: '11:00 AM - 01:00 PM', title: 'Distinguished Student Research Papers Presentation', room: 'Main Stage', speaker: 'Faculty Review Committee' },
      { id: 'sch-603', time: '02:00 PM - 04:00 PM', title: 'Industry Panel: What Top Tech Firms Seek in 2026 Graduates', room: 'Main Stage', speaker: 'Recruiting Directors' },
      { id: 'sch-604', time: '04:15 PM - 05:00 PM', title: 'Award Distribution & College Merit Badges', room: 'Main Stage', speaker: 'Principal Dr. Anushree Lokur' },
    ],
    tags: ['Leadership', 'Principal Summit', 'Research', 'Placements', 'Official'],
    isHackathon: false,
  },
  {
    id: 'evt-7',
    title: 'Inter-Department Rapid Blitz Chess Championship',
    description:
      'Official collegiate rapid chess tournament. 7 rounds Swiss system, 10 min + 5 sec increment. Cash trophies and college sports merit points awarded to top 5 players.',
    category: 'Sports',
    venueId: 'ven-6',
    venueName: 'Ruia Sports Academy & Gymkhana',
    building: 'Gymkhana Complex',
    bannerImage:
      'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&auto=format&fit=crop&q=80',
    startDate: '2026-11-20T10:00:00Z',
    endDate: '2026-11-20T18:00:00Z',
    registrationDeadline: '2026-11-18T18:00:00Z',
    capacity: 64,
    registeredCount: 0,
    price: 50,
    status: 'draft', // Draft status (FR3 & FR6 Showcase)
    organizerId: 'usr-organizer-1',
    organizerName: 'Priya Rao',
    organizerContact: {
      name: 'Sports Officer',
      email: 'gymkhana@ruiacollege.edu',
      phone: '+91 22 2414 3098',
      department: 'Ruia Gymkhana & Sports Council',
    },
    scheduleTimeline: [
      { id: 'sch-701', time: '10:00 AM - 10:30 AM', title: 'Pairing Announcements & Arbiters Briefing', room: 'Gymkhana Arena', speaker: 'Chief Arbiter' },
      { id: 'sch-702', time: '10:30 AM - 01:30 PM', title: 'Rounds 1 through 4', room: 'Gymkhana Boards 1-32', speaker: 'Tournament Arbiters' },
      { id: 'sch-703', time: '02:30 PM - 05:30 PM', title: 'Rounds 5 through 7 (Finals)', room: 'Gymkhana Boards 1-32', speaker: 'Tournament Arbiters' },
    ],
    tags: ['Chess', 'Sports', 'Rapid Tournament', 'Merit Points'],
    isHackathon: false,
  },
];

// ================= INITIAL REGISTRATIONS (FR8, FR9, FR10, FR15, FR16, FR22) =================
export const INITIAL_REGISTRATIONS: RegistrationRecord[] = [
  // Student 1 (Aarav Sharma)
  {
    id: 'reg-001',
    eventId: 'evt-1',
    eventTitle: 'TechNova 2026: National Hackathon & Innovation Summit',
    eventCategory: 'Technical',
    eventDate: 'Oct 15–16, 2026',
    eventVenue: 'Computer Science & IT Lab 4',
    studentId: 'usr-student-1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@ruiacollege.edu',
    studentIdNumber: 'RUIA-2023-CS084',
    registrationDate: '2026-09-02T10:15:00Z',
    status: 'confirmed',
    qrToken: 'RUIA26-EVT1-AARAV-CS084',
    checkInStatus: 'checked_in',
    checkInTime: '2026-10-15T08:42:00Z',
    paymentStatus: 'free',
    paymentAmount: 0,
    feedbackSubmitted: false,
  },
  {
    id: 'reg-002',
    eventId: 'evt-2',
    eventTitle: 'Cyber Defense & Ethical Hacking Hands-on Symposium',
    eventCategory: 'Seminar',
    eventDate: 'Oct 22, 2026',
    eventVenue: 'Dr. S. Radhakrishnan Seminar Hall',
    studentId: 'usr-student-1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@ruiacollege.edu',
    studentIdNumber: 'RUIA-2023-CS084',
    registrationDate: '2026-09-05T14:30:00Z',
    status: 'confirmed',
    qrToken: 'RUIA26-EVT2-AARAV-CS084',
    checkInStatus: 'not_checked_in',
    paymentStatus: 'paid',
    paymentAmount: 150,
    transactionRef: 'TXN-984128490-UPI',
    feedbackSubmitted: false,
  },
  {
    id: 'reg-003',
    eventId: 'evt-6',
    eventTitle: 'Principal’s Annual Academic & Innovation Summit',
    eventCategory: 'Academic',
    eventDate: 'Sep 10, 2026',
    eventVenue: 'Ruia College Auditorium',
    studentId: 'usr-student-1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@ruiacollege.edu',
    studentIdNumber: 'RUIA-2023-CS084',
    registrationDate: '2026-08-25T09:12:00Z',
    status: 'completed',
    qrToken: 'RUIA26-EVT6-AARAV-CS084',
    checkInStatus: 'checked_in',
    checkInTime: '2026-09-10T08:50:00Z',
    paymentStatus: 'free',
    paymentAmount: 0,
    feedbackSubmitted: true,
    feedbackRating: 5,
    feedbackComment: 'Exceptionally inspiring keynote and direct interaction with the Principal. Outstanding organization.',
    certificateId: 'cert-1001',
    certificateIssuedAt: '2026-09-10T17:30:00Z',
  },
  {
    id: 'reg-004',
    eventId: 'evt-3',
    eventTitle: 'Generative AI & Agentic Systems Masterclass',
    eventCategory: 'Workshop',
    eventDate: 'Oct 28, 2026',
    eventVenue: 'Computer Science & IT Lab 4',
    studentId: 'usr-student-1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@ruiacollege.edu',
    studentIdNumber: 'RUIA-2023-CS084',
    registrationDate: '2026-09-08T11:00:00Z',
    status: 'confirmed',
    qrToken: 'RUIA26-EVT3-AARAV-CS084',
    checkInStatus: 'not_checked_in',
    paymentStatus: 'paid',
    paymentAmount: 200,
    transactionRef: 'TXN-419082341-CARD',
    feedbackSubmitted: false,
  },

  // Student 2 (Diya Sen)
  {
    id: 'reg-005',
    eventId: 'evt-1',
    eventTitle: 'TechNova 2026: National Hackathon & Innovation Summit',
    eventCategory: 'Technical',
    eventDate: 'Oct 15–16, 2026',
    eventVenue: 'Computer Science & IT Lab 4',
    studentId: 'usr-student-2',
    studentName: 'Diya Sen',
    studentEmail: 'diya.sen@ruiacollege.edu',
    studentIdNumber: 'RUIA-2023-IT042',
    registrationDate: '2026-09-01T15:20:00Z',
    status: 'confirmed',
    qrToken: 'RUIA26-EVT1-DIYA-IT042',
    checkInStatus: 'checked_in',
    checkInTime: '2026-10-15T08:52:00Z',
    paymentStatus: 'free',
    paymentAmount: 0,
    feedbackSubmitted: false,
  },
  {
    id: 'reg-006',
    eventId: 'evt-4',
    eventTitle: 'Aarohan 2026: Annual Inter-Collegiate Cultural Festival',
    eventCategory: 'Cultural',
    eventDate: 'Nov 6–7, 2026',
    eventVenue: 'Historic Ruia Quadrangle & Open Stage',
    studentId: 'usr-student-2',
    studentName: 'Diya Sen',
    studentEmail: 'diya.sen@ruiacollege.edu',
    studentIdNumber: 'RUIA-2023-IT042',
    registrationDate: '2026-09-04T18:45:00Z',
    status: 'confirmed',
    qrToken: 'RUIA26-EVT4-DIYA-IT042',
    checkInStatus: 'not_checked_in',
    paymentStatus: 'free',
    paymentAmount: 0,
    feedbackSubmitted: false,
  },

  // Student 3 (Rohan Deshmukh)
  {
    id: 'reg-007',
    eventId: 'evt-1',
    eventTitle: 'TechNova 2026: National Hackathon & Innovation Summit',
    eventCategory: 'Technical',
    eventDate: 'Oct 15–16, 2026',
    eventVenue: 'Computer Science & IT Lab 4',
    studentId: 'usr-student-3',
    studentName: 'Rohan Deshmukh',
    studentEmail: 'rohan.d@ruiacollege.edu',
    studentIdNumber: 'RUIA-2024-EC105',
    registrationDate: '2026-09-03T12:00:00Z',
    status: 'confirmed',
    qrToken: 'RUIA26-EVT1-ROHAN-EC105',
    checkInStatus: 'checked_in',
    checkInTime: '2026-10-15T09:10:00Z',
    paymentStatus: 'free',
    paymentAmount: 0,
    feedbackSubmitted: false,
  },
  {
    id: 'reg-008',
    eventId: 'evt-2',
    eventTitle: 'Cyber Defense & Ethical Hacking Hands-on Symposium',
    eventCategory: 'Seminar',
    eventDate: 'Oct 22, 2026',
    eventVenue: 'Dr. S. Radhakrishnan Seminar Hall',
    studentId: 'usr-student-3',
    studentName: 'Rohan Deshmukh',
    studentEmail: 'rohan.d@ruiacollege.edu',
    studentIdNumber: 'RUIA-2024-EC105',
    registrationDate: '2026-09-06T16:10:00Z',
    status: 'cancelled',
    qrToken: 'RUIA26-EVT2-ROHAN-EC105',
    checkInStatus: 'not_checked_in',
    paymentStatus: 'refunded',
    paymentAmount: 150,
    transactionRef: 'TXN-771928340-REFUND',
    cancellationReason: 'Clashing semester mid-term lab practical examination schedule.',
  },
];

// ================= VOLUNTEER ASSIGNMENTS (FR20) =================
export const INITIAL_VOLUNTEERS: VolunteerAssignment[] = [
  {
    id: 'vol-1',
    eventId: 'evt-1',
    eventTitle: 'TechNova 2026: National Hackathon & Innovation Summit',
    studentId: 'usr-student-3',
    studentName: 'Rohan Deshmukh',
    studentEmail: 'rohan.d@ruiacollege.edu',
    role: 'Registration Desk',
    assignedBy: 'Priya Rao',
    assignedAt: '2026-09-05T10:00:00Z',
    status: 'confirmed',
  },
  {
    id: 'vol-2',
    eventId: 'evt-1',
    eventTitle: 'TechNova 2026: National Hackathon & Innovation Summit',
    studentId: 'usr-student-4',
    studentName: 'Kavya Pillai',
    studentEmail: 'kavya.p@ruiacollege.edu',
    role: 'Technical Support',
    assignedBy: 'Priya Rao',
    assignedAt: '2026-09-05T10:15:00Z',
    status: 'confirmed',
  },
  {
    id: 'vol-3',
    eventId: 'evt-2',
    eventTitle: 'Cyber Defense & Ethical Hacking Hands-on Symposium',
    studentId: 'usr-student-2',
    studentName: 'Diya Sen',
    studentEmail: 'diya.sen@ruiacollege.edu',
    role: 'Stage & Audio-Visual',
    assignedBy: 'Vikram Malhotra',
    assignedAt: '2026-09-07T11:20:00Z',
    status: 'confirmed',
  },
];

// ================= CERTIFICATES (FR17) =================
export const INITIAL_CERTIFICATES: CertificateRecord[] = [
  {
    id: 'cert-1001',
    certificateNumber: 'RUIA-CERT-2026-0891',
    registrationId: 'reg-003',
    eventId: 'evt-6',
    eventTitle: 'Principal’s Annual Academic & Innovation Summit',
    studentId: 'usr-student-1',
    studentName: 'Aarav Sharma',
    studentIdNumber: 'RUIA-2023-CS084',
    completionDate: 'September 10, 2026',
    issuerName: 'Dr. Anushree Lokur',
    issuerTitle: 'Principal, Ramnarain Ruia Autonomous College',
    verificationCode: 'VERIFY-8891-RUIA-CONFIRMED',
  },
];

// ================= POST-EVENT FEEDBACK (FR18) =================
export const INITIAL_FEEDBACK: EventFeedback[] = [
  {
    id: 'fb-1',
    eventId: 'evt-6',
    eventTitle: 'Principal’s Annual Academic & Innovation Summit',
    studentId: 'usr-student-1',
    studentName: 'Aarav Sharma',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    contentRating: 5,
    venueRating: 5,
    organizationRating: 5,
    reviewText:
      'Exceptionally inspiring keynote and direct interaction with the Principal. Outstanding organization and clear vision for collegiate research.',
    submittedAt: '2026-09-10T17:45:00Z',
  },
  {
    id: 'fb-2',
    eventId: 'evt-6',
    eventTitle: 'Principal’s Annual Academic & Innovation Summit',
    studentId: 'usr-student-2',
    studentName: 'Diya Sen',
    studentAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    rating: 4,
    contentRating: 5,
    venueRating: 4,
    organizationRating: 4,
    reviewText:
      'Loved the industry recruiting panel! Audio was clear throughout the auditorium, overall an invaluable experience.',
    submittedAt: '2026-09-10T18:10:00Z',
  },
];

// ================= NOTIFICATIONS & REMINDERS (FR12, FR14) =================
export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Room Update: Cyber Defense Symposium',
    message: 'The afternoon CTF practical drill will now take place in CS & IT Lab 4 due to network upgrade work.',
    type: 'event_update',
    timestamp: '2026-09-20T14:30:00Z',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Registration Confirmed: TechNova 2026',
    message: 'Your registration for TechNova 2026 is confirmed. Your digital QR entrance pass is now active.',
    type: 'registration',
    timestamp: '2026-09-15T09:00:00Z',
    read: true,
  },
  {
    id: 'notif-3',
    title: 'Certificate Ready: Principal’s Leadership Summit',
    message: 'Your official certificate of participation is now ready for verification and download.',
    type: 'certificate',
    timestamp: '2026-09-10T17:35:00Z',
    read: true,
  },
  {
    id: 'notif-4',
    title: 'New Event Approval Required',
    message: 'Organizer Vikram Malhotra submitted "Robotics & Autonomous Quadcopter Bootcamp" for administrative review.',
    type: 'approval',
    timestamp: '2026-09-18T11:15:00Z',
    read: false,
  },
];

// ================= LEGACY HACKATHON DATA (Retained for Hackathon Suite) =================
export const INITIAL_EVENT_INFO: EventInfo = {
  name: 'TechNova 2026',
  type: 'National Hackathon & Technology Summit',
  location: 'Ramnarain Ruia Autonomous College Campus, Matunga, Mumbai',
  venue: 'Computer Science & IT Lab 4 & Ruia Auditorium',
  dates: 'October 15–16, 2026',
  currentDay: 'Day 1 of 2 — Hacking & Mentorship Phase',
  status: 'Check-in Live',
  submissionDeadline: '2026-10-16T14:00:00.000Z',
  prizePool: '₹5,00,000 (~$6,000 USD)',
  totalTracks: 4,
};

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'p-1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@ruiacollege.edu',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    qrToken: 'RUIA26-EVT1-AARAV-CS084',
    role: 'AI / ML Engineer',
    primaryTrack: 'AI & Intelligent Systems',
    skills: ['PyTorch', 'Transformers', 'FastAPI', 'LangChain', 'Python', 'CUDA'],
    interests: ['Autonomous Agents', 'Multimodal LLMs', 'Edge AI', 'Voice Interfaces'],
    experienceLevel: 'Advanced',
    availability: 'In a Team',
    bio: 'ML researcher passionate about agentic AI workflows and low-latency inference. Building next-gen assistive healthcare bots.',
    github: 'https://github.com/aarav-ai',
    linkedin: 'https://linkedin.com/in/aaravsharma-ai',
    portfolio: 'https://aaravsharma.dev',
    checkInStatus: 'checked_in',
    checkInTime: '2026-10-15T08:45:00.000Z',
    teamId: 'team-1',
    connectionRequestsSent: ['p-5', 'p-8'],
    connectionRequestsReceived: ['p-3'],
    connections: ['p-2', 'p-4'],
  },
  {
    id: 'p-2',
    name: 'Diya Sen',
    email: 'diya.sen@ruiacollege.edu',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    qrToken: 'RUIA26-EVT1-DIYA-IT042',
    role: 'UI/UX Designer & Product Lead',
    primaryTrack: 'AI & Intelligent Systems',
    skills: ['Figma', 'Design Systems', 'Next.js', 'Tailwind CSS', 'User Research'],
    interests: ['Accessible Design', 'Micro-interactions', 'Data Visualization'],
    experienceLevel: 'Expert',
    availability: 'In a Team',
    bio: 'Lead product designer obsessed with intuitive user experiences for complex technical systems.',
    github: 'https://github.com/diyasen-design',
    linkedin: 'https://linkedin.com/in/diyasen',
    portfolio: 'https://diyasen.me',
    checkInStatus: 'checked_in',
    checkInTime: '2026-10-15T08:52:00.000Z',
    teamId: 'team-1',
    connectionRequestsSent: [],
    connectionRequestsReceived: [],
    connections: ['p-1', 'p-4'],
  },
  {
    id: 'p-3',
    name: 'Rohan Deshmukh',
    email: 'rohan.d@ruiacollege.edu',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    qrToken: 'RUIA26-EVT1-ROHAN-EC105',
    role: 'Backend Architect',
    primaryTrack: 'Web3 & Fintech',
    skills: ['Go', 'Rust', 'PostgreSQL', 'Docker', 'Kubernetes', 'gRPC'],
    interests: ['Distributed Systems', 'Zero Knowledge Proofs', 'High-throughput Trading'],
    experienceLevel: 'Advanced',
    availability: 'Looking for Team',
    bio: 'Ex-fintech infrastructure engineer. Looking for an AI engineer or UI designer to build a decentralized settlement engine.',
    github: 'https://github.com/rohand-dev',
    linkedin: 'https://linkedin.com/in/rohandeshmukh',
    checkInStatus: 'checked_in',
    checkInTime: '2026-10-15T09:10:00.000Z',
    connectionRequestsSent: ['p-1'],
    connectionRequestsReceived: [],
    connections: [],
  },
  {
    id: 'p-4',
    name: 'Kavya Pillai',
    email: 'kavya.p@ruiacollege.edu',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    qrToken: 'RUIA26-EVT1-KAVYA-CS019',
    role: 'Fullstack Developer',
    primaryTrack: 'AI & Intelligent Systems',
    skills: ['TypeScript', 'Next.js', 'Prisma', 'PostgreSQL', 'Python'],
    interests: ['Real-time Apps', 'Cloud Architecture', 'DevOps'],
    experienceLevel: 'Intermediate',
    availability: 'In a Team',
    bio: 'Fullstack engineer passionate about clean API contracts and responsive interfaces.',
    checkInStatus: 'checked_in',
    checkInTime: '2026-10-15T09:20:00.000Z',
    teamId: 'team-1',
    connectionRequestsSent: [],
    connectionRequestsReceived: [],
    connections: ['p-1', 'p-2'],
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-1',
    name: 'NeuralCrafters',
    tagline: 'Computer vision diagnostics for intra-operative surgical navigation',
    track: 'AI & Intelligent Systems',
    leaderId: 'p-1',
    members: [
      { participantId: 'p-1', name: 'Aarav Sharma', role: 'AI / ML Engineer', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', isLeader: true },
      { participantId: 'p-2', name: 'Diya Sen', role: 'UI/UX Designer', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80', isLeader: false },
      { participantId: 'p-4', name: 'Kavya Pillai', role: 'Fullstack Developer', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80', isLeader: false },
    ],
    maxMembers: 4,
    lookingForRoles: ['Embedded Hardware Engineer'],
    submissionId: 'sub-1',
    aggregateScore: 92.5,
    totalEvaluations: 2,
    rank: 1,
    previousRank: 1,
  },
  {
    id: 'team-2',
    name: 'EcoMesh',
    tagline: 'Decentralized peer-to-peer microgrid energy trading via LoRaWAN',
    track: 'Sustainable Tech',
    leaderId: 'p-3',
    members: [
      { participantId: 'p-3', name: 'Rohan Deshmukh', role: 'Backend Architect', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80', isLeader: true },
    ],
    maxMembers: 4,
    lookingForRoles: ['Frontend Developer', 'Firmware Engineer'],
    submissionId: 'sub-2',
    aggregateScore: 86.0,
    totalEvaluations: 1,
    rank: 2,
    previousRank: 2,
  },
];

export const INITIAL_SUBMISSIONS: ProjectSubmission[] = [
  {
    id: 'sub-1',
    teamId: 'team-1',
    teamName: 'NeuralCrafters',
    title: 'SurgiVision AI',
    tagline: 'Real-time anatomical boundary detection & tool tracking for laparoscopic procedures',
    track: 'AI & Intelligent Systems',
    problemStatement:
      'Laparoscopic surgery presents restricted fields of view and subtle anatomical boundaries, increasing accidental tissue perforation rates.',
    solution:
      'SurgiVision AI deploys low-latency edge vision models that segment critical vascular structures and highlight surgical instruments in under 12ms.',
    techStack: ['PyTorch', 'TensorRT', 'FastAPI', 'Next.js', 'WebRTC', 'Tailwind CSS'],
    repoUrl: 'https://github.com/neuralcrafters/surgivision-ai',
    demoUrl: 'https://surgivision.ruiacollege.edu',
    status: 'evaluated',
    submittedAt: '2026-10-16T13:45:00.000Z',
    coverImage: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'sub-2',
    teamId: 'team-2',
    teamName: 'EcoMesh',
    title: 'EcoMesh Microgrid Network',
    tagline: 'Decentralized smart solar sharing across residential microgrids',
    track: 'Sustainable Tech',
    problemStatement:
      'Excess residential solar power is dumped back to inefficient grids at punitive tariffs instead of powering neighboring consumers directly.',
    solution:
      'EcoMesh pairs cheap ESP32 energy meters with cryptographic settlement over lightweight consensus to automate neighbor-to-neighbor energy trading.',
    techStack: ['Rust', 'Go', 'MQTT', 'TimescaleDB', 'React', 'Tailwind CSS'],
    repoUrl: 'https://github.com/ecomesh/ecomesh-platform',
    status: 'evaluated',
    submittedAt: '2026-10-16T13:52:00.000Z',
    coverImage: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=800&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_JUDGES: Judge[] = [
  {
    id: 'j-1',
    name: 'Dr. Priya Sundaram',
    title: 'Senior Principal AI Researcher',
    company: 'Ruia Research & Innovation Center',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    track: 'AI & Intelligent Systems',
    assignedSubmissionIds: ['sub-1'],
  },
  {
    id: 'j-2',
    name: 'Karan Varma',
    title: 'VP of Engineering',
    company: 'GreenGrid Labs',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    track: 'Sustainable Tech',
    assignedSubmissionIds: ['sub-2'],
  },
];

export const INITIAL_EVALUATIONS: Evaluation[] = [
  {
    id: 'eval-1',
    submissionId: 'sub-1',
    teamId: 'team-1',
    judgeId: 'j-1',
    judgeName: 'Dr. Priya Sundaram',
    rubric: {
      innovation: 19,
      technicalImplementation: 24,
      problemRelevance: 19,
      userExperience: 14,
      impactAndFeasibility: 19,
    },
    totalScore: 95,
    feedback: 'Outstanding technical depth! The 12ms edge inference latency demonstration was rigorously executed.',
    strengths: ['Low inference latency', 'Clean medical-grade UI', 'Thorough edge optimization'],
    improvementAreas: ['Add clinical trial testing protocols', 'Hardware watchdog integration'],
    evaluatedAt: '2026-10-16T15:30:00.000Z',
  },
  {
    id: 'eval-2',
    submissionId: 'sub-2',
    teamId: 'team-2',
    judgeId: 'j-2',
    judgeName: 'Karan Varma',
    rubric: {
      innovation: 17,
      technicalImplementation: 21,
      problemRelevance: 18,
      userExperience: 13,
      impactAndFeasibility: 17,
    },
    totalScore: 86,
    feedback: 'Solid concept and smart use of lightweight MQTT protocols on edge hardware. Great market potential.',
    strengths: ['Resilient decentralized architecture', 'Practical renewable energy savings'],
    improvementAreas: ['UI telemetry visualization needs polish', 'Security auditing on peer nodes'],
    evaluatedAt: '2026-10-16T15:45:00.000Z',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'TechNova 2026: Day 1 Check-In Gates Active',
    message: 'Welcome all participating teams! Please present your scannable QR ticket at the CS & IT Lab 4 entrance.',
    priority: 'high',
    category: 'venue',
    timestamp: '2026-10-15T08:15:00.000Z',
    author: 'Priya Rao (Lead Organizer)',
    pinned: true,
  },
  {
    id: 'ann-2',
    title: 'CTF Lab Relocation Notice',
    message: 'Due to network upgrades, the Cyber Defense practical session will be held in CS & IT Lab 4.',
    priority: 'normal',
    category: 'schedule',
    timestamp: '2026-09-20T14:30:00.000Z',
    author: 'Vikram Malhotra',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    type: 'registration',
    title: 'Student Registered',
    description: 'Aarav Sharma registered for TechNova 2026',
    timestamp: '2026-09-02T10:15:00Z',
  },
  {
    id: 'act-2',
    type: 'check_in',
    title: 'Participant Checked In',
    description: 'Aarav Sharma verified at CS & IT Lab 4 gate desk',
    timestamp: '2026-10-15T08:42:00Z',
  },
  {
    id: 'act-3',
    type: 'event_approval',
    title: 'Event Approved',
    description: 'Principal Dr. Anushree Lokur approved "TechNova 2026" for publication',
    timestamp: '2026-09-01T09:00:00Z',
  },
];
